version: "3.8"

services:
  web:
    build: .
    command: >
        sh -c "python3 manage.py makemigrations &&
                python3 manage.py migrate &&
                python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
        POSTGRES_DB: ${NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
        - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  pgdata:
